name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'deploy'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/deploy'

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: HRKU-fa0e9a8c-51e4-4c47-8f24-135185b95d86
          heroku_app_name: shshsjsr12
          heroku_email: heuee694@gmail.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_OWNER_ID: ${{secrets.OWNER_ID}}
          HD_TELEGRAM_API: ${{secrets.TELEGRAM_API}}
          HD_TELEGRAM_HASH: ${{secrets.TELEGRAM_HASH}}
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
